# Complete list of all available properties: https://docs.platform.sh/create-apps/app-reference.html

# A unique name for the app. Must be lowercase alphanumeric characters. Changing the name destroys data associated
# with the app.
name: mercure

# The runtime the application uses.
# Complete list of available runtimes: https://docs.platform.sh/create-apps/app-reference.html#types
type: golang:1.18

# The size of the persistent disk of the application (in MB). Minimum value is 128.
disk: 1024

# Mounts define directories that are writable after the build is complete. If set as a local source, disk property is required.
# More information: https://docs.platform.sh/create-apps/app-reference.html#mounts
mounts:
  "database": { source: local, source_path: "database" }
  "/.local": { source: local, source_path: .local }
  "/.config": { source: local, source_path: .config }

# The web key configures the web server running in front of your app.
# More information: https://docs.platform.sh/create-apps/app-reference.html#web
web:
  commands:
    start: ./mercure run --config Caddyfile.platform_sh
  locations:
    /:
      allow: true
      scripts: false
      passthru: true
      request_buffering:
        enabled: false

# Define variables used by this app (env, runtime settings, ...)
# https://docs.platform.sh/create-apps/app-reference.html#variables
variables:
  env:
    MERCUREVERSION: 0.14.4
    SERVER_NAME: ":8888"
    MERCURE_TRANSPORT_URL: "bolt:///var/run/mercure.db"
    MERCURE_EXTRA_DIRECTIVES: |
      cors_origin *
      publish_origins *
      subscriptions
      demo
    GLOBAL_OPTIONS: |
      auto_https off
    MERCURE_PUBLISHER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
    MERCURE_SUBSCRIBER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"

# Specifies a default set of build tasks to run. Flavors are language-specific.
# More information: https://docs.platform.sh/create-apps/app-reference.html#build
build:
  flavor: none

# Hooks allow you to customize your code/environment as the project moves through the build and deploy stages
# More information: https://docs.platform.sh/create-apps/app-reference.html#hooks
hooks:
    build: |
      #Install Mercure using cache
      echo "${MERCUREVERSION}"
      FILE="mercure_${MERCUREVERSION}_Linux_x86_64.tar.gz"
      if [ ! -f "$PLATFORM_CACHE_DIR/$FILE" ]; then
        URL="https://github.com/dunglas/mercure/releases/download/v${MERCUREVERSION}/$FILE"
        echo "Downloading $URL"
        wget -O "$PLATFORM_CACHE_DIR/$FILE" $URL
      else
        echo "Found $FILE in cache, using cache"
      fi
      file $PLATFORM_CACHE_DIR/$FILE
      tar xvzf $PLATFORM_CACHE_DIR/$FILE

# Information on the app’s source code and operations that can be run on it.
# More information: https://docs.platform.sh/create-apps/app-reference.html#source
source:
  root: mercure/.config
